name: 📊 Path 1 - Observable estimations submission
description: Submit a problem solution to the observable estimations tracker - Trust through rigorous error control
labels: ['path: observable-estimations', 'submission']
body:
  - type: markdown
    attributes:
      value: |
        ## 📊 Path 1 - Observable estimations

        Thank you for submitting a solution to the **observable estimations tracker**!

        This pathway focuses on expectation-value experiments with mathematically grounded error bars. Your submission should demonstrate rigorous error control through techniques like QEC, QEM, or Post-Selected Error Detection.

        Please provide detailed information about your submission below.

  - type: input
    id: name
    attributes:
      label: Name
      description: Please provide a unique and identifiable name for your submission
    validations:
      required: true

  - type: dropdown
    id: circuit
    attributes:
      label: Circuit
      description: The problem instance this submission addresses
      options:
        - operator_loschmidt_echo_70x1872
        - operator_loschmidt_echo_49x648
        - operator_loschmidt_echo_49x1296
    validations:
      required: true

  - type: input
    id: observableValue
    attributes:
      label: Observable value
      description: The measured expectation value of the observable
      placeholder: e.g., "0.732"
    validations:
      required: true

  - type: input
    id: errorBoundLow
    attributes:
      label: Error bound (low)
      description: Lower error bound
      placeholder: e.g., "-0.05"
    validations:
      required: false

  - type: input
    id: errorBoundHigh
    attributes:
      label: Error bound (high)
      description: Upper error bound
      placeholder: e.g., "+0.05"
    validations:
      required: false

  - type: input
    id: method
    attributes:
      label: Method
      description: Name for the method used in submission
      placeholder: e.g., "Global rescaling"
    validations:
      required: true

  - type: textarea
    id: methodProof
    attributes:
      label: Method proof
      description: Link to paper, code repository, or detailed explanation of the method (required for verification)
      placeholder: |
        Provide at least one of:
        - Paper/preprint: https://arxiv.org/abs/...
        - Code repository: https://github.com/...
        - Method explanation: Detailed description of the approach
    validations:
      required: true

  - type: input
    id: authors
    attributes:
      label: Authors
      description: The author(s) or individual(s) involved in the submission, separated by commas
    validations:
      required: false

  - type: input
    id: institutions
    attributes:
      label: Institutions
      description: The institution(s) or organization(s) involved in the submission, separated by commas
    validations:
      required: true

  - type: input
    id: runtimeQuantum
    attributes:
      label: Quantum runtime (seconds)
      description: Quantum execution time in seconds
      placeholder: e.g., "5"
    validations:
      required: false

  - type: input
    id: runtimeClassical
    attributes:
      label: Classical runtime (seconds)
      description: Classical computation time in seconds
      placeholder: e.g., "9000"
    validations:
      required: false

  - type: input
    id: computeResourcesQuantum
    attributes:
      label: Compute resources (quantum)
      description: Quantum hardware specification
      placeholder: e.g., "IBM Heron r2"
    validations:
      required: false

  - type: input
    id: computeResourcesClassical
    attributes:
      label: Compute resources (classical)
      description: Classical hardware specification
      placeholder: e.g., "AMD EPYC 7763, 128 cores"
    validations:
      required: false

  - type: input
    id: notes
    attributes:
      label: Notes
      description: Additional notes
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        ### What happens next?

        Maintainers will review your submission for:
        - ✅ Reproducibility
        - ✅ Compliance with validation criteria
        - ✅ Data fidelity and traceability
        - ✅ Transparent documentation of assumptions and uncertainties

        Thank you for contributing to the Quantum Advantage Tracker! 🚀
