name: 🌀 Path 2 - Variational problems submission
description: Submit a problem solution to the variational problems tracker - Certifiable quantum solutions via the variational principle
labels: ['path: variational-problems', 'submission']
body:
  - type: markdown
    attributes:
      value: |
        ## 🌀 Path 2 - Variational problems

        Thank you for submitting a solution to the **variational problems tracker**!

        This pathway focuses on guaranteed solution bounds and benchmarking against classical methods. Your submission should demonstrate variational bounds (energy values as upper bounds to true ground-state energy).

        Please provide detailed information about your submission below.

  - type: input
    id: name
    attributes:
      label: Name
      description: Please provide a unique and identifiable name for your submission
    validations:
      required: true

  - type: dropdown
    id: hamiltonian
    attributes:
      label: Hamiltonian
      description: The hamiltonian this submission addresses
      options:
        - 4fe_4s_54e_36o
        - anderson_impurity_model_4i_28b_32e
    validations:
      required: true

  - type: input
    id: qubits
    attributes:
      label: Qubits
      description: Number of qubits
      placeholder: e.g., "49"
    validations:
      required: false

  - type: input
    id: gates
    attributes:
      label: Gates
      description: Number of gates
      placeholder: e.g., "648"
    validations:
      required: false

  - type: input
    id: energy
    attributes:
      label: Energy (Eh)
      description: The ground-state energy value (upper bound), measured in Eh.
      placeholder: e.g., "-7.8823"
    validations:
      required: true

  - type: input
    id: errorBoundLow
    attributes:
      label: Low error bound (Eh)
      description: Lower error bound, measured in Eh
      placeholder: e.g., "-0.05"
    validations:
      required: false

  - type: input
    id: errorBoundHigh
    attributes:
      label: High error bound (Eh)
      description: Upper error bound, measured in Eh
      placeholder: e.g., "+0.05"
    validations:
      required: false

  - type: input
    id: method
    attributes:
      label: Method
      description: Name for the method used in submission
      placeholder: e.g., "SQD"
    validations:
      required: true

  - type: textarea
    id: methodProof
    attributes:
      label: Method proof
      description: Link to paper, code repository, or detailed explanation of the method (required for verification). If method is Quantum, please attach the circuit.
      placeholder: |
        Provide at least one of:
        - Paper/preprint: https://arxiv.org/abs/...
        - Code repository: https://github.com/...
        - Method explanation: Detailed description of the approach
    validations:
      required: true

  - type: input
    id: institutions
    attributes:
      label: Institutions
      description: The institution(s) or organization(s) involved in the submission, separated by commas
      placeholder:
    validations:
      required: true

  - type: input
    id: runtimeQuantum
    attributes:
      label: Quantum runtime (seconds)
      description: Quantum execution time in seconds
      placeholder: e.g., "5"
    validations:
      required: false

  - type: input
    id: runtimeClassical
    attributes:
      label: Classical runtime (seconds)
      description: Classical computation time in seconds
      placeholder: e.g., "9000"
    validations:
      required: false

  - type: input
    id: computeResourcesQuantum
    attributes:
      label: Compute resources (quantum)
      description: Quantum hardware specification
      placeholder: e.g., "IBM Heron r2"
    validations:
      required: false

  - type: input
    id: computeResourcesClassical
    attributes:
      label: Compute resources (classical)
      description: Classical hardware specification
      placeholder: e.g., "AMD EPYC 7763, 128 cores"
    validations:
      required: false

  - type: input
    id: notes
    attributes:
      label: Notes
      description: Additional notes
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        ### What happens next?

        Maintainers will review your submission for:
        - ✅ Reproducibility
        - ✅ Compliance with validation criteria (variational property)
        - ✅ Data fidelity and traceability
        - ✅ Transparent documentation of assumptions and uncertainties

        Thank you for contributing to the Quantum Advantage Tracker! 🚀
